all:
	gcc sender_sigalrm.c  -o sender_sigalrm.out
	gcc receiver_sigalrm.c  -o receiver_sigalrm.out
	gcc sender_select.c  -o sender_select.out
	gcc receiver_select.c  -o receiver_select.out
	gcc sender_sockopt.c  -o sender_sockopt.out
	gcc receiver_sockopt.c  -o receiver_sockopt.out

clean:
	rm -f sender_sigalrm.out
	rm -f receiver_sigalrm.out
	rm -f sender_select.out
	rm -f receiver_select.out
	rm -f sender_sockopt.out
	rm -f receiver_sockopt.out
